### ISSUE TITLE
VSD CLI

### ISSUE THREAD

**Issue by marcowenwolf** [nuagenetworks/vspk-python#27]
LS,

running the following vsd cli command results into a TLS error, which is caused likely because the VSD CLI https request does not handle the SSL version correctly. Please check how to ensure VSD CLI supports TLS 1.2 version:

[stack@nl-gv-pbl-t1-sdn-nvu01 ~]$ vsd list enterprises
Traceback (most recent call last):
  File "/usr/bin/vsd", line 9, in <module>
    load_entry_point('vspk==5.0.1', 'console_scripts', 'vsd')()
  File "/usr/lib/python2.7/site-packages/vspk/cli/cli.py", line 134, in main
    CLICommand.execute(args)
  File "/usr/lib/python2.7/site-packages/vspk/cli/commands.py", line 44, in execute
    func(args)
  File "/usr/lib/python2.7/site-packages/vspk/cli/commands.py", line 56, in list
    session = inspector.get_user_session(args)
  File "/usr/lib/python2.7/site-packages/vspk/cli/utils.py", line 256, in get_user_session
    session.start()
  File "/usr/lib/python2.7/site-packages/bambou-2.1.3-py2.7.egg/bambou/nurest_session.py", line 170, in start
    self._authenticate()
  File "/usr/lib/python2.7/site-packages/bambou-2.1.3-py2.7.egg/bambou/nurest_session.py", line 141, in _authenticate
    self._root_object.fetch()
  File "/usr/lib/python2.7/site-packages/bambou-2.1.3-py2.7.egg/bambou/nurest_root_object.py", line 190, in fetch
    connection = self.send_request(request=request)
  File "/usr/lib/python2.7/site-packages/bambou-2.1.3-py2.7.egg/bambou/nurest_object.py", line 770, in send_request
    return connection.start()
  File "/usr/lib/python2.7/site-packages/bambou-2.1.3-py2.7.egg/bambou/nurest_connection.py", line 439, in start
    return self._make_request(session=session)
  File "/usr/lib/python2.7/site-packages/bambou-2.1.3-py2.7.egg/bambou/nurest_connection.py", line 373, in _make_request
    response = self.__make_request(method=self._request.method, url=self._request.url, params=self._request.params, data=data, headers=headers, certificate=certificate)
  File "/usr/lib/python2.7/site-packages/bambou-2.1.3-py2.7.egg/bambou/nurest_connection.py", line 417, in __make_request
    cert=certificate)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:579)

Using vspk or curl commands result into the correct behavior using TLS version 1.0, 1.1 and 1.2. Version 1.2 is accepted for hardened VSD servers using TLS version 1.2 only.

Would it be possible to provide a workaround using TLS version 1.2?

**Comment by pdellaert** [comment]
Thanks @marcowenwolf, that's good feedback. We'll look into this.
