### ISSUE TITLE
async new keywork in python >3.6 causes problems

### ISSUE THREAD

**Issue by marcowenwolf** [nuagenetworks/vspk-python#42]
Hallo,

I run into an fixed problem described in:
https://github.com/nuagenetworks/vspk-python/issues/32

It is working on python 3.6
```
nuage-cats-5.4.1) marcwolf@laptop:~/git/SCIP/scip-sdn-vsdlib> python
Python 3.6.10 (default, Jan 16 2020, 09:12:04) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import VSDLib
>>> quit()
(nuage-cats-5.4.1) marcwolf@laptop:~/git/SCIP/scip-sdn-vsdlib> python --version; pip freeze | grep -e vspk -e bambou
Python 3.6.10
bambou==3.1.1
vspk==20.5.2
(nuage-cats-5.4.1) marcwolf@laptop:~/git/SCIP/scip-sdn-vsdlib> python
Python 3.6.10 (default, Jan 16 2020, 09:12:04) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import VSDLib
>>> quit
```

related to the new async python keywork. This is my config:

```
(nuage-cats-5.4.1) cats@catsvm:~/venvs/nuage-cats-5.4.1/lib/python3.8/site-packages/VSDLib$ python --version; pip freeze | grep -e vspk -e bambou
Python 3.8.5
bambou==3.1.2
vspk==20.10.1
```

I have defined a function based on vspk:

```
       def  create_child(self, obj, nutype, **kwargs):
        """Create child vspk object
        
        Arguments:
        - obj -- the parent object
        - nutype -- child vspk class 
        - kwargs -- variable number of arguments to be passed to the child constructor 
    
        Returns:
        - child object
        
        Examples:
        | ${r} = | Create Child | obj=enterprise | nutype=NUDomain | name=My domain | description=Test |
        """
        child = vsdk.__dict__[nutype](**kwargs)
        obj.create_child(child, async=False)
        return child
```

```
    (nuage-cats-5.4.1) cats@catsvm:~/venvs/nuage-cats-5.4.1/lib/python3.8/site-packages/VSDLib$ python
    Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
    [GCC 9.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import VSDLib
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/cats/venvs/nuage-cats-5.4.1/lib/python3.8/site-packages/VSDLib/__init__.py", line 14, in <module>
        from .vsdlib import VSDLib
      File "/home/cats/venvs/nuage-cats-5.4.1/lib/python3.8/site-packages/VSDLib/vsdlib.py", line 205
        obj.create_child(child, async=False)
                            ^
    SyntaxError: invalid syntax
```

**Comment by pdellaert** [comment]
For Python 3.7 and above, you must use `as_async=False` instead of `async=False` because `async` has become a reserved word. Also, `async`/`as_async` is by default `False`, you don't need to explicitly set it to `False`

**Comment by marcowenwolf** [comment]
Thanks, not sure what would be a good way to communicate these kind of changes. How many might be still out there running into this issue if moving towards 3.7 or higher.

**Comment by pdellaert** [comment]
We've highlighted this to our teams working with customers and internally using the available internal e-mail lists... I agree this isn't easily available to the outside world. Need to look into how we can improve on that.
